### ISSUE TITLE
Revert dependencies between aggregate_root and rails_event_store

### ISSUE THREAD

**Issue by andrzejkrzywda** [arkency/aggregate_root#2]
At the moment, `aggregate_root` depends on `rails_event_store` (as in it lists RES as dependency in the gemspec).

The consequences are that if you want to use aggregates with RES, you need to depend on the `aggregate_root` gem in your app.

What I'd like to discuss here is the idea of reverting this dependency.

`rails_event_store` could then become an umbrella gem for all the smaller things, like:

* aggregates support
* commands support
* read models support
* event browser 

In that case, you would be able to use any of those small gems, without bringing the RES (RailsEventStore) as the dependency to your project. People could grab the `aggregate_root` gem and use it with their own event stores, as long as the interfaces match.

`aggregate_root` now depends on some "interfaces of RailsEventStore, but it doesn't need to depend on the actual RES implementation.

RailsEventStore as the umbrella project would be similar to ... ekhem, Rails.The name wouldn't be precise, as it's more than an event store, but in this vision it's more like DDD/CQRS/ES infrastructure support.

Marketing-wise, we would focus on promoting RailsEventStore as an easy-to-drop in a Rails app tool, which enables you to start doing DDD/CQRS/ES. 

Any thoughts?

**Comment by paneq** [comment]
I would propose inventing new name for the umbrella gem, and keep the dependencies as they are right now.

**Comment by mpraglowski** [comment]
> What I'd like to discuss here is the idea of reverting this dependency.

@andrzejkrzywda you might be right, the dependency here should bot be explicit
The main reason for me is that we should be able to replace [rails_event_store](https://github.com/arkency/rails_event_store) with [http_eventstore](https://github.com/arkency/http_eventstore)

We might have default_event_store in application configuration and not have strong dependency on RES.

> RailsEventStore as the umbrella project 

I'm not fully convinced yet. It would be "umbrella project" that implements 1/4 of the scope of gems that might be under it. Marketing-wise, of course, it will make sense.


So my thoughts:
* `aggregate_root` should not have a dependency on `rails_event_store`
* I'm not sure if `rails_event_store` will be the best "umbrella"

**Comment by mpraglowski** [comment]
Done
